name: Cobertura Alta

on:
  workflow_dispatch:

jobs:
  cobertura-alta:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes com cobertura
        run: npm test

      - name: Quality Gate
        run: |
          COVERAGE=$(node -e "const s=require('./coverage/coverage-summary.json'); console.log(s.total.lines.pct)")
          echo "Cobertura: $COVERAGE%"

          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Falhou"
            exit 1
          else
            echo "Aprovado"
          fi